# Gizli Dirichlet Dağılımı (Latent Dirichlet Allocation) (LDA)

🎯 Bu challenge'ın amacı, **LDA** algoritması (NLP'de Denetimsiz Öğrenme) ile e-posta külliyatı içinde konular bulmaktır.

✉️ İşte 1000'den fazla ***etiketlenmemiş e-posta*** içeren bir koleksiyon. Bunlardan ***konuları çıkarmaya*** çalışalım!

In [12]:
import pandas as pd

url = 'https://d32aokrjazspmn.cloudfront.net/materials/lda_data'

data = pd.read_csv(url, sep=",", header=None)
data.columns = ['text']
data.head()

                                                text
0  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...
1  From: atterlep@vela.acs.oakland.edu (Cardinal ...
2  From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...
3  From: atterlep@vela.acs.oakland.edu (Cardinal ...
4  From: vzhivov@superior.carleton.ca (Vladimir Z...

In [13]:
data.shape

(1199, 1)

## (1) Preprocessing

❓ **Question (Cleaning**) ❓ You're used to it by now... Clean up! Store the cleaned text in a new column "clean_text" of the DataFrame.

In [14]:
# SENİN KODUN BURAYA
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/elifcubukcu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/elifcubukcu/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/elifcubukcu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/elifcubukcu/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [20]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words('english'))

In [ ]:
def clean(text):

    text = text.translate(str.maketrans('', '', string.punctuation))

    text = text.lower()

    tokens = word_tokenize(text)

    words_only = [word for word in tokens if word.isalpha() ]

    without_stopword = [ word for word in words_only if word not in stop_words]

    lemmatized = [lemmatizer.lemmatize(word) for word in without_stopword]

    return ' '.join(lemmatized)

data['cleaned_data'] = data['text'].apply(clean)
data.head()

,text,cleaned_data
0,From: gld@cunixb.cc.columbia.edu (Gary L Dare)...,gldcunixbcccolumbiaedu gary l dare subject sta...
1,From: atterlep@vela.acs.oakland.edu (Cardinal ...,atterlepvelaacsoaklandedu cardinal ximenez sub...
2,From: miner@kuhub.cc.ukans.edu\nSubject: Re: A...,minerkuhubccukansedu subject ancient book orga...
3,From: atterlep@vela.acs.oakland.edu (Cardinal ...,atterlepvelaacsoaklandedu cardinal ximenez sub...
4,From: vzhivov@superior.carleton.ca (Vladimir Z...,vzhivovsuperiorcarletonca vladimir zhivov subj...

## (2) Latent Dirichlet Allocation model

❓ **Soru (Eğitim)** ❓ Potansiyel konuları çıkarmak için bir LDA modeli eğitin

In [19]:
vectorizer = CountVectorizer()

data_vectorized = vectorizer.fit_transform(data['cleaned_data'])

In [21]:
lda_model = LatentDirichletAllocation(n_components=2)

In [22]:
lda_vectors = lda_model.fit_transform(data_vectorized)

##  (3) Potansiyel konuları görselleştirin

🎁 Potansiyel konularla ilişkili kelimeleri yazdırmak için bir  fonksiyon kodladık.

In [23]:
def print_topics(model, vectorizer):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                        for i in topic.argsort()[:-10 - 1:-1]])

❓ **Soru** ❓ LDA tarafından çıkarılan konuları yazdırın.

In [24]:
print_topics(lda_model, vectorizer )

Topic 0:
[('team', 953.4959617659345), ('game', 923.708597574576), ('line', 708.255564768218), ('subject', 633.2814189953451), ('organization', 611.8549615581269), ('hockey', 594.4925520137742), ('player', 524.4668837860852), ('play', 495.6762811499722), ('year', 436.27452707422776), ('university', 425.97216413201977)]
Topic 1:
[('god', 1489.4728048335028), ('one', 837.1470816575396), ('would', 810.5814317949962), ('christian', 758.4682657786309), ('people', 700.6531268109301), ('subject', 673.7185810046062), ('line', 635.7444352317342), ('jesus', 623.4899808810047), ('organization', 559.1450384418235), ('say', 540.6284484905357)]

## (4) Yeni bir metnin belge-konu karışımını tahmin edin

❓ **Soru (Tahmin)** ❓

LDA modeliniz fit edildiğine göre, onu yeni bir metnin konularını tahmin etmek için kullanabilirsiniz.

1. Örneği vektörleştirin
2. Vektörleştirilmiş örnek üzerinde LDA'yı kullanarak konuları tahmin edin

In [25]:
example = ["My team performed poorly last season. Their best player was out injured and only played one game"]

In [27]:
example_vectorized = vectorizer.transform(example)

example_lda_vector = lda_model.transform(example_vectorized)

In [28]:
print('topic 0: ', example_lda_vector[0][0])
print('topic 1: ', example_lda_vector[0][1])

topic 0:  0.9518213384444983
topic 1:  0.04817866155550158

🏁 Tebrikler! LDA'yı hızlı bir şekilde nasıl uygulayacağınızı öğrendiniz.

💾 Not defterinizi `git add/commit/push` yapmayı unutmayın...

🚀 ... ve bir sonraki göreve geçin!